// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: researchPaper.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_researchPaper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_researchPaper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_researchPaper_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Paper struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ShortDescription string                 `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	PaperLink        string                 `protobuf:"bytes,4,opt,name=paper_link,json=paperLink,proto3" json:"paper_link,omitempty"`
	ResearcherID     int32                  `protobuf:"varint,5,opt,name=researcherID,proto3" json:"researcherID,omitempty"`
	PublishYear      int32                  `protobuf:"varint,6,opt,name=publishYear,proto3" json:"publishYear,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Paper) Reset() {
	*x = Paper{}
	mi := &file_researchPaper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paper) ProtoMessage() {}

func (x *Paper) ProtoReflect() protoreflect.Message {
	mi := &file_researchPaper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paper.ProtoReflect.Descriptor instead.
func (*Paper) Descriptor() ([]byte, []int) {
	return file_researchPaper_proto_rawDescGZIP(), []int{1}
}

func (x *Paper) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Paper) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Paper) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Paper) GetPaperLink() string {
	if x != nil {
		return x.PaperLink
	}
	return ""
}

func (x *Paper) GetResearcherID() int32 {
	if x != nil {
		return x.ResearcherID
	}
	return 0
}

func (x *Paper) GetPublishYear() int32 {
	if x != nil {
		return x.PublishYear
	}
	return 0
}

type ListofPapers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Papers        []*Paper               `protobuf:"bytes,1,rep,name=papers,proto3" json:"papers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListofPapers) Reset() {
	*x = ListofPapers{}
	mi := &file_researchPaper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListofPapers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListofPapers) ProtoMessage() {}

func (x *ListofPapers) ProtoReflect() protoreflect.Message {
	mi := &file_researchPaper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListofPapers.ProtoReflect.Descriptor instead.
func (*ListofPapers) Descriptor() ([]byte, []int) {
	return file_researchPaper_proto_rawDescGZIP(), []int{2}
}

func (x *ListofPapers) GetPapers() []*Paper {
	if x != nil {
		return x.Papers
	}
	return nil
}

var File_researchPaper_proto protoreflect.FileDescriptor

const file_researchPaper_proto_rawDesc = "" +
	"\n" +
	"\x13researchPaper.proto\x12\x05hello\x1a\x1bgoogle/protobuf/empty.proto\"!\n" +
	"\x05state\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbf\x01\n" +
	"\x05Paper\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"paper_link\x18\x04 \x01(\tR\tpaperLink\x12\"\n" +
	"\fresearcherID\x18\x05 \x01(\x05R\fresearcherID\x12 \n" +
	"\vpublishYear\x18\x06 \x01(\x05R\vpublishYear\"4\n" +
	"\fListofPapers\x12$\n" +
	"\x06papers\x18\x01 \x03(\v2\f.hello.PaperR\x06papers2V\n" +
	"\rResearchPaper\x12E\n" +
	"\x14GetAllResearchPapers\x12\x16.google.protobuf.Empty\x1a\x13.hello.ListofPapers\"\x00B\fZ\n" +
	"/protobufsb\x06proto3"

var (
	file_researchPaper_proto_rawDescOnce sync.Once
	file_researchPaper_proto_rawDescData []byte
)

func file_researchPaper_proto_rawDescGZIP() []byte {
	file_researchPaper_proto_rawDescOnce.Do(func() {
		file_researchPaper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_researchPaper_proto_rawDesc), len(file_researchPaper_proto_rawDesc)))
	})
	return file_researchPaper_proto_rawDescData
}

var file_researchPaper_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_researchPaper_proto_goTypes = []any{
	(*State)(nil),         // 0: hello.state
	(*Paper)(nil),         // 1: hello.Paper
	(*ListofPapers)(nil),  // 2: hello.ListofPapers
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_researchPaper_proto_depIdxs = []int32{
	1, // 0: hello.ListofPapers.papers:type_name -> hello.Paper
	3, // 1: hello.ResearchPaper.GetAllResearchPapers:input_type -> google.protobuf.Empty
	2, // 2: hello.ResearchPaper.GetAllResearchPapers:output_type -> hello.ListofPapers
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_researchPaper_proto_init() }
func file_researchPaper_proto_init() {
	if File_researchPaper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_researchPaper_proto_rawDesc), len(file_researchPaper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_researchPaper_proto_goTypes,
		DependencyIndexes: file_researchPaper_proto_depIdxs,
		MessageInfos:      file_researchPaper_proto_msgTypes,
	}.Build()
	File_researchPaper_proto = out.File
	file_researchPaper_proto_goTypes = nil
	file_researchPaper_proto_depIdxs = nil
}
