// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: researchPaper.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResearchPaper_GetAllResearchPapers_FullMethodName       = "/hello.ResearchPaper/GetAllResearchPapers"
	ResearchPaper_GetResearchPaperByCategory_FullMethodName = "/hello.ResearchPaper/GetResearchPaperByCategory"
	ResearchPaper_GetResearchPaperByID_FullMethodName       = "/hello.ResearchPaper/GetResearchPaperByID"
	ResearchPaper_CreateResearchPaper_FullMethodName        = "/hello.ResearchPaper/CreateResearchPaper"
	ResearchPaper_DeleteResearchPaper_FullMethodName        = "/hello.ResearchPaper/DeleteResearchPaper"
)

// ResearchPaperClient is the client API for ResearchPaper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type ResearchPaperClient interface {
	// Sends a greeting
	GetAllResearchPapers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListofPapers, error)
	GetResearchPaperByCategory(ctx context.Context, in *GetResearchPaperByCategoryRequest, opts ...grpc.CallOption) (*ListofPapers, error)
	GetResearchPaperByID(ctx context.Context, in *GetResearchPaperByIDRequest, opts ...grpc.CallOption) (*Paper, error)
	CreateResearchPaper(ctx context.Context, in *CreateResearchPaperRequest, opts ...grpc.CallOption) (*CreateResearchPaperResponse, error)
	DeleteResearchPaper(ctx context.Context, in *DeleteResearchPaperRequest, opts ...grpc.CallOption) (*State, error)
}

type researchPaperClient struct {
	cc grpc.ClientConnInterface
}

func NewResearchPaperClient(cc grpc.ClientConnInterface) ResearchPaperClient {
	return &researchPaperClient{cc}
}

func (c *researchPaperClient) GetAllResearchPapers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListofPapers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListofPapers)
	err := c.cc.Invoke(ctx, ResearchPaper_GetAllResearchPapers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *researchPaperClient) GetResearchPaperByCategory(ctx context.Context, in *GetResearchPaperByCategoryRequest, opts ...grpc.CallOption) (*ListofPapers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListofPapers)
	err := c.cc.Invoke(ctx, ResearchPaper_GetResearchPaperByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *researchPaperClient) GetResearchPaperByID(ctx context.Context, in *GetResearchPaperByIDRequest, opts ...grpc.CallOption) (*Paper, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Paper)
	err := c.cc.Invoke(ctx, ResearchPaper_GetResearchPaperByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *researchPaperClient) CreateResearchPaper(ctx context.Context, in *CreateResearchPaperRequest, opts ...grpc.CallOption) (*CreateResearchPaperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResearchPaperResponse)
	err := c.cc.Invoke(ctx, ResearchPaper_CreateResearchPaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *researchPaperClient) DeleteResearchPaper(ctx context.Context, in *DeleteResearchPaperRequest, opts ...grpc.CallOption) (*State, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(State)
	err := c.cc.Invoke(ctx, ResearchPaper_DeleteResearchPaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResearchPaperServer is the server API for ResearchPaper service.
// All implementations must embed UnimplementedResearchPaperServer
// for forward compatibility.
//
// The greeting service definition.
type ResearchPaperServer interface {
	// Sends a greeting
	GetAllResearchPapers(context.Context, *emptypb.Empty) (*ListofPapers, error)
	GetResearchPaperByCategory(context.Context, *GetResearchPaperByCategoryRequest) (*ListofPapers, error)
	GetResearchPaperByID(context.Context, *GetResearchPaperByIDRequest) (*Paper, error)
	CreateResearchPaper(context.Context, *CreateResearchPaperRequest) (*CreateResearchPaperResponse, error)
	DeleteResearchPaper(context.Context, *DeleteResearchPaperRequest) (*State, error)
	mustEmbedUnimplementedResearchPaperServer()
}

// UnimplementedResearchPaperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResearchPaperServer struct{}

func (UnimplementedResearchPaperServer) GetAllResearchPapers(context.Context, *emptypb.Empty) (*ListofPapers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllResearchPapers not implemented")
}
func (UnimplementedResearchPaperServer) GetResearchPaperByCategory(context.Context, *GetResearchPaperByCategoryRequest) (*ListofPapers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResearchPaperByCategory not implemented")
}
func (UnimplementedResearchPaperServer) GetResearchPaperByID(context.Context, *GetResearchPaperByIDRequest) (*Paper, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResearchPaperByID not implemented")
}
func (UnimplementedResearchPaperServer) CreateResearchPaper(context.Context, *CreateResearchPaperRequest) (*CreateResearchPaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResearchPaper not implemented")
}
func (UnimplementedResearchPaperServer) DeleteResearchPaper(context.Context, *DeleteResearchPaperRequest) (*State, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResearchPaper not implemented")
}
func (UnimplementedResearchPaperServer) mustEmbedUnimplementedResearchPaperServer() {}
func (UnimplementedResearchPaperServer) testEmbeddedByValue()                       {}

// UnsafeResearchPaperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResearchPaperServer will
// result in compilation errors.
type UnsafeResearchPaperServer interface {
	mustEmbedUnimplementedResearchPaperServer()
}

func RegisterResearchPaperServer(s grpc.ServiceRegistrar, srv ResearchPaperServer) {
	// If the following call pancis, it indicates UnimplementedResearchPaperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResearchPaper_ServiceDesc, srv)
}

func _ResearchPaper_GetAllResearchPapers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchPaperServer).GetAllResearchPapers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchPaper_GetAllResearchPapers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchPaperServer).GetAllResearchPapers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResearchPaper_GetResearchPaperByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResearchPaperByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchPaperServer).GetResearchPaperByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchPaper_GetResearchPaperByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchPaperServer).GetResearchPaperByCategory(ctx, req.(*GetResearchPaperByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResearchPaper_GetResearchPaperByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResearchPaperByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchPaperServer).GetResearchPaperByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchPaper_GetResearchPaperByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchPaperServer).GetResearchPaperByID(ctx, req.(*GetResearchPaperByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResearchPaper_CreateResearchPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResearchPaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchPaperServer).CreateResearchPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchPaper_CreateResearchPaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchPaperServer).CreateResearchPaper(ctx, req.(*CreateResearchPaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResearchPaper_DeleteResearchPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResearchPaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearchPaperServer).DeleteResearchPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResearchPaper_DeleteResearchPaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearchPaperServer).DeleteResearchPaper(ctx, req.(*DeleteResearchPaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResearchPaper_ServiceDesc is the grpc.ServiceDesc for ResearchPaper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResearchPaper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.ResearchPaper",
	HandlerType: (*ResearchPaperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllResearchPapers",
			Handler:    _ResearchPaper_GetAllResearchPapers_Handler,
		},
		{
			MethodName: "GetResearchPaperByCategory",
			Handler:    _ResearchPaper_GetResearchPaperByCategory_Handler,
		},
		{
			MethodName: "GetResearchPaperByID",
			Handler:    _ResearchPaper_GetResearchPaperByID_Handler,
		},
		{
			MethodName: "CreateResearchPaper",
			Handler:    _ResearchPaper_CreateResearchPaper_Handler,
		},
		{
			MethodName: "DeleteResearchPaper",
			Handler:    _ResearchPaper_DeleteResearchPaper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "researchPaper.proto",
}
